### PR TITLE
Respect quadruple time signature & BPM of OST

### PR DESCRIPTION
**Pull request by pepijn**

### CODE REVIEW

**Comment by ghost** [comment]
:+1:

**Comment by jelmerkoppelmans** [comment]
:+1:

**Comment by pepijn** [comment]
Wanneer gaat de animatie nou eindelijk over op een vierkwartsmaat? Merge pls :tired_face:

**Comment by ghost** [comment]
No PRs have been merged in the last 10 months, maybe we could contact the maintainer to allow more contributors to this project or we might have to consider forking.

**Comment by pepijn** [comment]
The maintainer is indeed blatantly neglecting his responsibilities with regards to the future of this open source project. For this reason, I do side with you, @pnicolai, on the forking notion. Power to the people!!!11

**Comment by tursunovic** [comment]
@rickpastoor durf te maintainen

**Comment by rickpastoor** [comment]
I'm sorry guys. This is a complex project and I have to consider changes like this from all angles. Talked about this change with the board and it got approved just now. Merging right away.

Keep your changes coming.

**Pull request merged**
